Globalize.addCultureInfo("default", 
{
        messages:
        {
            // automatically generated by JSON.stringify(DevExpress.localization.getDictionary(true), null, 4)
            "AboutUs": "About Us"
            , "FXQuote": "FX Quote"
            , "Shop" : "FX Shop"
            , "Currency" : "Currency"
            , "TT" : "TT"
            , "Cash": "Cash"
            , "Bid" : "Bid"
            , "Ask": "Ask"
            , "UpdTime": "Upd.Time"
            , "UserRegistration": "User Registration"
            , "Err.Connect": "Can't Connect To Server"
            , "dxList-noDataText" : "No Data To Display"
            , "CCY_AUD": "AUD"
            , "CCY_CAD": "CAD"
            , "CCY_CHF": "CHF"
            , "CCY_CNY": "CNY"
            , "CCY_DKK": "DKK"
            , "CCY_EUR": "EUR"
            , "CCY_GBP": "GBP"
            , "CCY_JPY": "JPY"
            , "CCY_NOK": "NOK"
            , "CCY_NZD": "NZD"
            , "CCY_SEK": "SEK"
            , "CCY_SGD": "SGD"
            , "CCY_USD": "USD"
            , "SHOP_FX0": "FX-Change (Cost)"
            , "SHOP_FX1": "FX-Change (Client)"
            , "SHOP_FXC": "FX-Change"
            , "SHOP_HSBC": "HSBC"
        }
});
